import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'

// registerSW.js (auto-generated by vite-plugin-pwa) registers the service
// worker; this just makes sure that once a newly-deployed worker takes over
// (see the skipWaiting/clientsClaim pair in src/sw.js), the already-open tab
// reloads once to actually fetch the new app bundle, instead of continuing to
// run the old JS already loaded in memory.
//
// Guarded on hadController: clientsClaim() also fires 'controllerchange' the
// very first time a service worker claims a previously-uncontrolled page
// (first-ever visit, or right after this page's own initial load) — that's
// not a stale-content situation (the page already has fresh assets from the
// network), so reloading then would just be a pointless extra reload. Only a
// page that already had an active controller and then got handed a *new*
// one is actually running stale cached code.
if ('serviceWorker' in navigator) {
  const hadController = !!navigator.serviceWorker.controller;
  let reloaded = false;
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    if (!hadController || reloaded) return;
    reloaded = true;
    window.location.reload();
  });
}

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
